name: Auto review PRs

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  auto-review:
    permissions:
      contents: read
      pull-requests: write   # ※ レビューを投稿するので write 必須
      id-token: write
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Auto review PR (Claude Sonnet 4, OAuth)
        uses: grll/claude-code-action@b6027fe73e663ec60bcc0ccb6fe91c001bf91878  # ← fork 版 & commit pin
        with:
          use_oauth: true
          claude_access_token:  ${{ secrets.CLAUDE_ACCESS_TOKEN }}
          claude_refresh_token: ${{ secrets.CLAUDE_REFRESH_TOKEN }}
          claude_expires_at:    ${{ secrets.CLAUDE_EXPIRES_AT }}
          model: "claude-sonnet-4-20250514"
          direct_prompt: |
            Please review this PR. Look at the changes and provide thoughtful feedback on:
            - Code quality and best practices
            - Potential bugs or issues
            - Suggestions for improvements
            - Overall architecture and design decisions

            Be constructive and specific in your feedback. Give inline comments where applicable.
          allowed_tools: |
            mcp__github__create_pending_pull_request_review,
            mcp__github__add_pull_request_review_comment_to_pending_review,
            mcp__github__submit_pending_pull_request_review,
            mcp__github__get_pull_request_diff
